### ISSUE TITLE
can't run windows client (win7 winxp)

### ISSUE THREAD

**Issue by maqiangddb** [01org/KVMGT-kernel#12]
qemu cmd:
sudo x86_64-softmmu/qemu-system-x86_64 -bios roms/seabios/out/bios.bin -m 1024 -M pc -smp 2 -enable-kvm -cpu host -machine kernel_irqchip=on -vgt -vga vgt -cdrom /home/mq/cn_windows_7_ultimate_with_sp1_x86_dvd_u_677486.iso -hda /home/mq/qemu_img/win7_disk.img

virtual machine show:
![img_20150204_163130](https://cloud.githubusercontent.com/assets/2367812/6037175/7caebd8a-ac8b-11e4-851c-09baaef61925.jpg)

Dose KVMGT-seabios need do some change?

**Comment by l1viathan** [comment]
We don't have windows support yet.    Even for linux guest, you need have PPGTT disable via kernel cmdline, e.g.  "i915.enable_ppgtt=0" or something alike.

**Comment by maqiangddb** [comment]
if XenGT support windows? Does this work in progress?

**Comment by maqiangddb** [comment]
sorry，I just read this file http://www.linux-kvm.org/wiki/images/f/f3/01x08b-KVMGT-a.pdf
In TODO list：
Implement shadow PPGTT
 Is a must to support Windows guest

Looking forward KVMGT support Windows guest! Good job！
