### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by tcwu2005** [01org/KVMGT-kernel#23]
Does KVMGT support android (ex. Android x86) ??

I roughly know android x86 porting based on Linux DRM , however, not pretty much sure that KVMGT supports Android x86 or not.

**Comment by l1viathan** [comment]
currently not. Only Core platform supported, not SoC.

**Comment by tcwu2005** [comment]
Hi Jike, 
  My description might not be very clear.
  Android x86 is an open source project.  Plz see here.  (http://www.android-x86.org/)
  I have run android x86 in qemu on Intel i7, and there is no GPU acceleration.  (I need GPU acceleration in Android x86 guest OS for some applications).

**Comment by l1viathan** [comment]
Aha, thanks for the correction :)

As long as supported CPU used -  Currently on Haswell, Broadwell will come soon - KVMGT should be there.

You are running android-x86 on Linux, right?  If your CPU is supported, and KVM is used, then KVMGT should work for you. 

However, by "should work" I mean guest OS is capable to find an Intel GPU, submitting GPU commands to it. I didn't mean that everything necessary is already contained by guest OS :)

**Comment by tcwu2005** [comment]
Hi Jike, 
Thanks for reply.  Yes we run android this way: android x86 - qemu - linux - hardware Intel i7.
According to your reply, I guess guest OS (i.e. Android x86) can find Intel GPU rather than some other generic software render but a correct driver might be needed...
I will install KVMGT on my experimental PC to test it.  Thanks to you again.
