### ISSUE TITLE
Support for generation 8 (gen8)

### ISSUE THREAD

**Issue by tcwu2005** [01org/KVMGT-kernel#24]
For using KVMGT we purchase a brand-new i7 machine and I encounter following errors
1. 
  [   61.132078] WARNING: CPU: 2 PID: 1331 at drivers/gpu/drm/i915/i915_drv.c:494 i915_semaphore_is_enabled+0x37/0x5c()
2. 
And I trace i915_drv.c ,Line 494
    if (IS_GEN8(dev)) {
        WARN_ON(!i915_preliminary_hw_support);
        return false;
    }
3. 
And then I enable CONFIG_DRM_I915_PRELIMINARY_HW_SUPPORT=y.
4. Finally it boots and give me a black screen.  (I can attach its dmesg log later)  

Does it support Intel graphic generation 8?  If not , do you have a plan or schedule?
Also, would you like to guide me how to tell gpu generations (chip id? cli command?)?

Thank you.

**Comment by tcwu2005** [comment]
Here is dmsg files 
file 'dmsg' -CONFIG_DRM_I915_PRELIMINARY_HW_SUPPORT not set
![dmsg](https://cloud.githubusercontent.com/assets/13940041/9714939/5be06976-558e-11e5-9211-d49a9886c438.png)
file 'dmsg2' -CONFIG_DRM_I915_PRELIMINARY_HW_SUPPORT=y
![dmsg2](https://cloud.githubusercontent.com/assets/13940041/9714940/5be2656e-558e-11e5-871d-952a7c299862.png)

**Comment by l1viathan** [comment]
GEN8 is the gpu of BDW. This repo doesn't contain GEN8 support, but it probably will be contained in Q3 release(supposed to be at early October).

**Comment by tcwu2005** [comment]
Thanks for reply.
I built kvmgt on a older machine.  
It successfully boot.  However there is only one resolution:640x480.  
Is this normal? 

![xxx](https://cloud.githubusercontent.com/assets/13940041/9757909/03819afa-5716-11e5-902e-c70882b19bd3.png)

**Comment by l1viathan** [comment]
host or guest? I guess something was wrong.

**Comment by tcwu2005** [comment]
Host.  I am downloading ubuntu14 image so that I haven't tried guest.

I attached `dmesg` (dmesg >log; mv log log.png; upload log.png)
![dmesg ivgt](https://cloud.githubusercontent.com/assets/13940041/9758515/bbad9b08-5719-11e5-9050-146d33ef9690.png)
You might take a look if you want; Or, if you can give a hardware guide it's also very good so that I can look for a right cpu.

**Comment by l1viathan** [comment]
kvm host is native, you should see same behaviors for kvmgt host as for native.

**Comment by tcwu2005** [comment]
Thanks Jike.  I will do some debugging and report back.

**Comment by tcwu2005** [comment]
The hardware configuration was not correct.  I replace it with another machine, and will report my latest status back.  And I am closing this issue.
